services:
  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: salon_os
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

